In [1]:
function base(n,N)
    a=zeros(N)
    a[n]=1
    return a
end

base (generic function with 1 method)

In [2]:
base(1,2)

2-element Array{Float64,1}:
 1.0
 0.0

In [3]:
kron(base(2+1,7).*base(2,7)',base(1,2).*base(1,2)')+kron(base(2-1,7).*base(2,7)',base(2,2).*base(2,2)')

14×14 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

In [4]:
S=zeros(Float64,200,200)

for i in 2:100-1
    S=S+kron(base(i+1,100).*base(i,100)',base(1,2)*base(1,2)')+kron(base(i-1,100)*base(i,100)',base(2,2).*base(2,2)')
end
S

200×200 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.

In [14]:
I=eye(100,100)
H=(1/sqrt(2))*[1 1; 1 -1]

    
    for i in 2:100-1
    p=(kron(base(i,100)',base(1,2)'))*(((S*kron(I,H))^3)*kron(base(2,100),base(1,2)))+(kron(base(i,100)',base(2,2)')*(((S*kron(I,H))^3)*kron(base(2,100),base(2,2))))
    
    
        push!(listP,p)
        
    end
    
        return listP
    

LoadError: MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.

In [15]:
proba_cuantica(3)

LoadError: MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.

In [7]:
I=eye(100,100)
H=(1/sqrt(2))*[1 1; 1 -1]
p=(kron(base(3,100)',base(1,2)'))*(((S*kron(I,H))^3)*kron(base(2,100),base(1,2)))+(kron(base(3,100)',base(2,2)')*(((S*kron(I,H))^3)*kron(base(2,100),base(2,2))))
    return p
    

1-element Array{Float64,1}:
 0.707107

In [8]:
I=eye(10,10)
H=(1/sqrt(2))*[1 1; 1 -1]
ux0=((S*kron(I,H))^3)*kron(base(3,10),base(1,2))

LoadError: DimensionMismatch("A has dimensions (200,200) but B has dimensions (20,20)")

In [9]:
x=kron(base(2,5)',base(1,2)')

1×10 Array{Float64,2}:
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [10]:
x*ux0

LoadError: UndefVarError: ux0 not defined

In [11]:
kron(base(2,5)',base(1,2)')

1×10 Array{Float64,2}:
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0