# Ejercicio 1

Crear la libreria herramientas dentro de su carpeta de tareas, en su repositorio. Dentro deberán poner los métodos de Newton que construyeron, los métodos de integración, Euler independiente de dimensión (implícito y explícito)y Runge-Kutta independiente de dimensión. Recuerden que las rutinas deben funcionar solo con sus argumentos, no debe haber variables globales, todo lo que necesite la función para trabajar debe ser un argumento o una variable definida internamente.

# Mètodo de Newton

In [1]:
__precompile__() # Este comando es para que julia precompile el paquete

module herramientas

export metodo_newton

"""documentación del método de Newton para calcular las raices para el pozo finito cuadrado con A=10.0"""

#Calcula las raices para el pozo finito cuadrado con A=10.0

function metodo_newton(s)
    x=s;
    f(x)=x*tan(x)-sqrt(complex(10.0-x^2))+im -im;
    for i in 1:100
        df=complex(x*sec(x)^2+x/sqrt(complex(10.0-x^2))+tan(x)) #Esto se hizo para evitar errores de dominio
        x=x-f(x)/df;
    end
    return x,f(x)
end
end


herramientas

In [2]:
herramientas.metodo_newton(0.1)

(3.1616420951060653 - 4.761032580504596e-19im,-3.802513859341161e-15 + 0.0im)

In [3]:
?herramientas.metodo_newton

documentación del método de Newton para calcular las raices para el pozo finito cuadrado con A=10.0


In [4]:
import herramientas.jl

In [5]:
herramientas.metodo_newton(0.1)

(3.1616420951060653 - 4.761032580504596e-19im,-3.802513859341161e-15 + 0.0im)

In [1]:
__precompile__() # Este comando es para que julia precompile el paquete

module herramientas

export biseccion

"""documentación del Mètodo de Bisecciòn"""

#Este programa también grafica la convergencia de las raices para 4 condiciones inciales, pero utilizando el método de Bisección.

function biseccion(a,b)
    p = (a+b)/2
    f(x) = x^3-x^2-x-1
    list=zeros(50)
    for i in 1:50
        if  f(a)*f(p) > 0 
            a = p
        end;
        
        if f(b)*f(p) > 0
            b = p
        end;
        p = (a+b)/2
        list[i]=p
    end;
    return (list-list[50])./list[50]  #Este calculo se hizo para obtener el error relativo a la raiz
end

end

herramientas

In [2]:
herramientas.biseccion(0,5)

50-element Array{Float64,1}:
 -0.320389   
  0.0194169  
 -0.150486   
 -0.0655345  
 -0.0230588  
 -0.00182095 
  0.00879797 
  0.00348851 
  0.000833778
 -0.000493588
  0.000170095
 -0.000161746
  4.17465e-6 
  ⋮          
  1.30502e-12
  6.88122e-14
 -5.49291e-13
 -2.40239e-13
 -8.57135e-14
 -8.45062e-15
  3.01808e-14
  1.08651e-14
  1.20723e-15
 -3.6217e-15 
 -1.20723e-15
  0.0        

In [3]:
?herramientas.biseccion

documentación del Mètodo de Bisecciòn


In [4]:
import herramientas.jl

In [5]:
herramientas.biseccion(0,5)

50-element Array{Float64,1}:
 -0.320389   
  0.0194169  
 -0.150486   
 -0.0655345  
 -0.0230588  
 -0.00182095 
  0.00879797 
  0.00348851 
  0.000833778
 -0.000493588
  0.000170095
 -0.000161746
  4.17465e-6 
  ⋮          
  1.30502e-12
  6.88122e-14
 -5.49291e-13
 -2.40239e-13
 -8.57135e-14
 -8.45062e-15
  3.01808e-14
  1.08651e-14
  1.20723e-15
 -3.6217e-15 
 -1.20723e-15
  0.0        

# Mètodos de Integraciòn

In [1]:
__precompile__() # Este comando es para que julia precompile el paquete

module herramientas

export Metodo_del_rectangulo

"""documentación del Método del Rectàngulo"""

#Este programa calcula el valor aproximado de la integral con el Método del rectángulo, el cual consiste en sumar las áreas de todos los rectángulos formados bajo la curva. La base de cada rectángulo corresponde a una diferencia finita de un subintervalo y la altura a la función evaluada en el punto que se encuentra a la mitad del subintervalo [a,b].

function Metodo_del_rectangulo(f,c)
    i=1 
    I=0 #Se inicia la suma en I=0
    for i in 1:length(c)-1 #Se utilizó un for para ir iterando los valores de los subintervalos tomados del intervalo c
        a=c[i] # a corresponde al límite inferior del subintervalo [a,b] y c[] localiza al primer elemento del subintervalo.
        b=c[i+1] # b es el límte superior del subintervalo y c[i+1] incrementa en 1 al valor anterior y con ello localiza al                       segundo elemento del subintervalo, y así sucesivamente para todos los demás.
        I=I+(b-a)*f((a+b)/2) #La aproximación a la integral por este método, ésta dada por la fórmula I. 
    end
        return I #Devuelve el valor de la integral como la suma de todos los rectángulos de diferencia finita.
    
end
end

herramientas

In [2]:
herramientas.Metodo_del_rectangulo(x->x^3+x^2+1,linspace(1,10,20))

2838.805055401662

In [3]:
?herramientas.Metodo_del_rectangulo

documentación del Método del Rectàngulo


In [4]:
import herramientas.jl

In [5]:
herramientas.Metodo_del_rectangulo(x->x^3+x^2+1,linspace(1,10,20))

2838.805055401662

In [1]:
__precompile__() # Este comando es para que julia precompile el paquete

module herramientas

export Metodo_del_trapecio

"""documentación del Método del Trapecio"""

function Metodo_del_trapecio(f,c)
    i=1
    I=0 #Se inicia la suma en I=0
    for i in 1:length(c)-1 #Se usó un for para iterar los valores del subintervalo, ya que estos valores serán usados en la suma                            de las áreas de todos los trapecios.
        a=c[i] # a es el límite superior del subintervalo 
        b=c[i+1] # b es el límite inferior del subintervalo
        I=I+(b-a)*(f(a)+f(b))/2 # I corresponde a la suma de todas las áreas de los trapecios.
    end
    return I #Devuelve el valor de la integral
end
end

herramientas

In [2]:
herramientas.Metodo_del_trapecio(x->x^3+x^2+1,linspace(1,10,20))

2847.639889196676

In [3]:
?herramientas.Metodo_del_trapecio

documentación del Método del Trapecio


In [4]:
import herramientas.jl

In [5]:
herramientas.Metodo_del_trapecio(x->x^3+x^2+1,linspace(1,10,20))

2847.639889196676

In [1]:
__precompile__() # Este comando es para que julia precompile el paquete

module herramientas

export Metodo_Simpson

"""documentación del Método de Simpson"""

#Este progrma utliza la regla de Simpson para obtener una aproximación a la integral y sigue el mismo procedimiento que los anteriores, pero aproximando los subintervalos de f mediante polinomios de segundo grado.

function Metodo_Simpson(f,c)
    i=1
    I=0
    for i in 1:length(c)-1 #Con el uso de for se iteraron los valores del subintervalo para que la fórmula I los tome y los                                 evalue.
        a=c[i] # a corresponde al límite inferior del subintervalo
        b=c[i+1] # b es el límite superior del subintervalo
        I=I+((b-a)/6)*[f(a)+4*f((a+b)/2)+f(b)] #Consideramos el polinomio interpolador de orden dos que aproxima a la función                                                   integrando f(x) en los puntos a y b. Aplicando el método de interpolación de                                                     Lagrange, que para tres puntos interpola con un polinomio de grado 2 se obtiene                                                 la fórmula I.
    end
    return I #Devueleve el valor de I
end
end

herramientas

In [2]:
herramientas.Metodo_Simpson(x->x^3+x^2+1,linspace(1,10,20))

1-element Array{Float64,1}:
 2841.75

In [3]:
?herramientas.Metodo_Simpson

documentación del Método de Simpson


In [4]:
import herramientas.jl

In [5]:
herramientas.Metodo_Simpson(x->x^3+x^2+1,linspace(1,10,20))

1-element Array{Float64,1}:
 2841.75

# Mètodo de Euler independiente de dimensión (implícito y explícito)

In [1]:
__precompile__() # Este comando es para que julia precompile el paquete

module herramientas

export euler_explicito

"""documentación Euler explicito"""

function euler_explicito(f,list,x0)
     x = x0
     h = list[2]-list[1]
     listx=[]
     push!(listx,x)
     for i in 2:length(list)
        t = i*h
        x = x + f(x,t)*h
        push!(listx,x) 
     end
     return listx
end
end

herramientas

In [2]:
f(x,t)=[1.0*x[2], -1.0*x[1]-1.0*x[2]]

f (generic function with 1 method)

In [3]:
herramientas.euler_explicito(f,0:0.01:100,[0,1])

10001-element Array{Any,1}:
 [0,1]                     
 [0.01,0.99]               
 [0.0199,0.98]             
 [0.0297,0.970001]         
 [0.0394,0.960004]         
 [0.049,0.95001]           
 [0.0585001,0.94002]       
 [0.0679003,0.930035]      
 [0.0772007,0.920055]      
 [0.0864012,0.910083]      
 [0.0955021,0.900118]      
 [0.104503,0.890162]       
 [0.113405,0.880215]       
 ⋮                         
 [-2.59004e-22,2.6579e-22] 
 [-2.56346e-22,2.65722e-22]
 [-2.53688e-22,2.65629e-22]
 [-2.51032e-22,2.65509e-22]
 [-2.48377e-22,2.65365e-22]
 [-2.45723e-22,2.65195e-22]
 [-2.43072e-22,2.65e-22]   
 [-2.40422e-22,2.64781e-22]
 [-2.37774e-22,2.64537e-22]
 [-2.35128e-22,2.64269e-22]
 [-2.32486e-22,2.63978e-22]
 [-2.29846e-22,2.63663e-22]

In [4]:
?herramientas.euler_explicito

documentación Euler explicito


In [5]:
import herramientas.jl

In [6]:
herramientas.euler_explicito(f,0:0.01:100,[0,1])

10001-element Array{Any,1}:
 [0,1]                     
 [0.01,0.99]               
 [0.0199,0.98]             
 [0.0297,0.970001]         
 [0.0394,0.960004]         
 [0.049,0.95001]           
 [0.0585001,0.94002]       
 [0.0679003,0.930035]      
 [0.0772007,0.920055]      
 [0.0864012,0.910083]      
 [0.0955021,0.900118]      
 [0.104503,0.890162]       
 [0.113405,0.880215]       
 ⋮                         
 [-2.59004e-22,2.6579e-22] 
 [-2.56346e-22,2.65722e-22]
 [-2.53688e-22,2.65629e-22]
 [-2.51032e-22,2.65509e-22]
 [-2.48377e-22,2.65365e-22]
 [-2.45723e-22,2.65195e-22]
 [-2.43072e-22,2.65e-22]   
 [-2.40422e-22,2.64781e-22]
 [-2.37774e-22,2.64537e-22]
 [-2.35128e-22,2.64269e-22]
 [-2.32486e-22,2.63978e-22]
 [-2.29846e-22,2.63663e-22]

In [1]:
__precompile__() # Este comando es para que julia precompile el paquete

module herramientas

export euler_implicito

"""documentación Euler implicito"""

function euler_implicito(f,df,list,x0)
     x = x0
     h = list[2]-list[1]
     listx=[]
     push!(listx,x)
     for i in 2:length(list)
        t = i*h
       x = x -(x-f(x,t)*h)/df(x)
        push!(listx,x) 
     end
     return listx
end
end

herramientas

In [2]:
f(x,t)=3*(x[2])^2+x+1

f (generic function with 1 method)

In [3]:
df(x)=6x[2]+1

df (generic function with 1 method)

In [4]:
herramientas.euler_implicito(f,df,0:0.01:100,[0,1])

10001-element Array{Any,1}:
 [0,1]                
 [0.00571429,0.864286]
 [0.0100392,0.7312]   
 [0.0130279,0.601661] 
 [0.0147551,0.476978] 
 [0.0153293,0.35906]  
 [0.0149146,0.250765] 
 [0.0137651,0.15639]  
 [0.0122722,0.0820521]
 [0.0109672,0.0344551]
 [0.0102861,0.0145046]
 [0.0101233,0.0104999]
 [0.0101057,0.0101315]
 ⋮                    
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]

In [5]:
?herramientas.euler_implicito

documentación Euler implicito


In [6]:
import herramientas.jl

In [7]:
herramientas.euler_implicito(f,df,0:0.01:100,[0,1])

10001-element Array{Any,1}:
 [0,1]                
 [0.00571429,0.864286]
 [0.0100392,0.7312]   
 [0.0130279,0.601661] 
 [0.0147551,0.476978] 
 [0.0153293,0.35906]  
 [0.0149146,0.250765] 
 [0.0137651,0.15639]  
 [0.0122722,0.0820521]
 [0.0109672,0.0344551]
 [0.0102861,0.0145046]
 [0.0101233,0.0104999]
 [0.0101057,0.0101315]
 ⋮                    
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]
 [0.0101041,0.0101041]

# Runge-Kutta independiente de dimensión

In [1]:
__precompile__() # Este comando es para que julia precompile el paquete

module herramientas

export euler_implicito

"""documentación Runge-Kutta de orden 4"""

function RK4(f,list,x0)
     x = x0
     h = list[2]-list[1]
     listx=[]
     push!(listx,x)
     for i in 2:length(list)
        t=i*h
        k1=f(x,t);
        k2=f(x+(h/2)*k1,t+(h/2));
        k3=f(x+(h/2)*k2,t+(h/2));
        k4=f(x+h*k3,t+h);
        x = x + (h/6)*(k1+2*k2+2*k3+k4);
        push!(listx,x) 
    end
     return listx
end
end

herramientas

In [2]:
f(x,t)=[x[2], -sin(x[1])]

f (generic function with 1 method)

In [3]:
herramientas.RK4(f,0:0.01:100,[0,1])

10001-element Array{Any,1}:
 [0,1]               
 [0.00999983,0.99995]
 [0.0199987,0.9998]  
 [0.0299955,0.99955] 
 [0.0399893,0.9992]  
 [0.0499792,0.998751]
 [0.059964,0.998201] 
 [0.0699429,0.997552]
 [0.0799147,0.996803]
 [0.0898786,0.995955]
 [0.0998335,0.995008]
 [0.109778,0.993962] 
 [0.119712,0.992817] 
 ⋮                   
 [-0.967498,0.367047]
 [-0.963786,0.375271]
 [-0.959992,0.383474]
 [-0.956117,0.391655]
 [-0.952159,0.399813]
 [-0.948121,0.407948]
 [-0.944001,0.416059]
 [-0.9398,0.424146]  
 [-0.935518,0.432208]
 [-0.931155,0.440244]
 [-0.926713,0.448254]
 [-0.92219,0.456237] 

In [4]:
?herramientas.RK4

documentación Runge-Kutta de orden 4


In [5]:
import herramientas.jl

In [6]:
herramientas.RK4(f,0:0.01:100,[0,1])

10001-element Array{Any,1}:
 [0,1]               
 [0.00999983,0.99995]
 [0.0199987,0.9998]  
 [0.0299955,0.99955] 
 [0.0399893,0.9992]  
 [0.0499792,0.998751]
 [0.059964,0.998201] 
 [0.0699429,0.997552]
 [0.0799147,0.996803]
 [0.0898786,0.995955]
 [0.0998335,0.995008]
 [0.109778,0.993962] 
 [0.119712,0.992817] 
 ⋮                   
 [-0.967498,0.367047]
 [-0.963786,0.375271]
 [-0.959992,0.383474]
 [-0.956117,0.391655]
 [-0.952159,0.399813]
 [-0.948121,0.407948]
 [-0.944001,0.416059]
 [-0.9398,0.424146]  
 [-0.935518,0.432208]
 [-0.931155,0.440244]
 [-0.926713,0.448254]
 [-0.92219,0.456237] 